name: verifier_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pytest
      - flake8
      - flake8-json
      - mypy
      - coverage
      - hypothesis
      - mutmut
      - pytest-cov
      - pylint
      - bandit
      - radon
      - black
      - rich
      - python-patch
      - unidiff
      - docker
      - pytest-xdist
      - datasets
