name: verifier_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - pip=25.2
  - setuptools=78.1.1
  - wheel=0.45.1
  # Core packages
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - openssl=3.5.4
  - sqlite=3.50.2
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - xz=5.6.4
  - zlib=1.3.1
  - expat=2.7.1
  - krb5=1.21.3
  # Python packages
  - colorama=0.4.6
  - six=1.17.0
  - packaging=25.0
  - pip:
      # Core dependencies
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - altair==5.5.0
      - anyio==4.11.0
      - astroid==3.3.11
      - asttokens==3.0.0
      - attrs==25.4.0
      - bandit==1.8.6
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - cbor2==5.7.1
      - certifi==2025.10.5
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - comm==0.2.3
      - contourpy==1.3.3
      - coverage==7.10.7
      - cycler==0.12.1
      - datasets==4.1.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.4.0
      - distlib==0.4.0
      - docker==7.1.0
      - exceptiongroup==1.3.0
      - execnet==2.1.1
      - executing==2.2.1
      - fastcore==1.8.14
      - filelock==3.19.1
      - flake8==7.3.0
      - flake8-json==24.4.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ghapi==1.0.8
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpclib==0.4.8
      - h2==4.3.0
      - hpack==4.1.0
      - huggingface-hub==0.35.3
      - hyperframe==6.1.0
      - hypothesis==6.140.3
      - identify==2.6.15
      - idna==3.10
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipykernel==6.30.1
      - ipython==9.6.0
      - ipython_pygments_lexers==1.1.1
      - isort==6.1.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter_client==8.6.3
      - jupyter_core==5.8.1
      - kiwisolver==1.4.9
      - libcst==1.7.0
      - linkify-it-py==2.0.3
      - mando==0.7.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - modal==1.2.1
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mutmut==3.3.1
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - narwhals==2.9.0
      - nest-asyncio==1.6.0
      - nodeenv==1.9.1
      - numpy==2.3.3
      - pandas==2.3.3
      - parso==0.8.5
      - pathspec==0.12.1
      - pickleshare==0.7.5
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.0
      - protobuf==6.33.0
      - psutil==7.1.0
      - pure_eval==0.2.3
      - pyarrow==21.0.0
      - pycodestyle==2.14.0
      - pydeck==0.9.1
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pylint==3.3.9
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - pytest-xdist==3.8.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytokens==0.1.10
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - radon==6.0.1
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.1.0
      - rpds-py==0.27.1
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - sigtools==4.0.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - stack_data==0.6.3
      - stevedore==5.5.0
      - streamlit==1.50.0
      - git+https://github.com/SWE-bench/SWE-bench.git@5cd4be9fb23971679cbbafe5a0ecade27cef99be#egg=swebench
      - synchronicity==0.10.2
      - tenacity==9.1.2
      - textual==6.2.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.20.0
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - unidiff==0.7.5
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
